# Generated by Django 3.2.12 on 2024-04-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Time', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
