# Generated by Django 3.2.12 on 2024-04-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
