# Generated by Django 3.2.12 on 2024-04-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20240404_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Deleted',
            field=models.BooleanField(default=False),
        ),
    ]
